version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Passw0rd_dev!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: always

volumes:
  mssql_data:
